# Generated by Django 4.1.7 on 2023-03-22 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('class_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=10)),
                ('number_of_student', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('login_name', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('teacher_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('fullname', models.CharField(max_length=50)),
                ('year_of_birth', models.IntegerField()),
                ('sex', models.CharField(max_length=3)),
                ('start_work_year', models.IntegerField()),
                ('academic_title', models.CharField(max_length=50)),
                ('major', models.CharField(max_length=70)),
                ('classes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HomePage.class')),
            ],
        ),
    ]
