# Generated by Django 4.1.7 on 2023-05-17 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note_class',
            name='name',
            field=models.DateField(max_length=50),
        ),
        migrations.AlterField(
            model_name='note_student',
            name='name',
            field=models.DateField(max_length=50),
        ),
    ]
