# Generated by Django 4.1.7 on 2023-05-17 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0002_alter_note_class_name_alter_note_student_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university_class',
            name='teacher_note',
        ),
    ]
