# Generated by Django 4.1.7 on 2023-05-21 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0003_remove_university_class_teacher_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='lastname',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
