# Generated by Django 4.1.7 on 2023-05-24 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0004_student_lastname'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='is_done_adding_class',
            field=models.BooleanField(default=True),
        ),
    ]
