# Generated by Django 4.1.7 on 2023-05-24 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0005_teacher_is_done_adding_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='is_done_adding_class',
        ),
        migrations.AddField(
            model_name='university_class',
            name='is_done',
            field=models.BooleanField(default=True),
        ),
    ]
